### ISSUE TITLE
Fix error after running npx: Error: EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by peterthehan** [peterthehan/runescape-text#7]
Error output after running npx:
```
internal/fs/utils.js:307
    throw err;
    ^

Error: EPERM: operation not permitted, unlink 'C:\Users\Peter\AppData\Roaming\npm-cache\_npx\13284\node_modules\runescape-text\node_modules\canvas\build\Release\canvas.node'
    at Object.unlinkSync (fs.js:1210:3)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:219:13)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5 
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:7)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:217:5)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5 
{
  errno: -4048,
  syscall: 'unlink',
  code: 'EPERM',
  path: 'C:\\Users\\Peter\\AppData\\Roaming\\npm-cache\\_npx\\13284\\node_modules\\runescape-text\\node_modules\\canvas\\build\\Release\\canvas.node'
}
```
Not sure what this is. Does not occur running locally `node src/cli.js "my message"`

Windows 10, node v14.15.4, npx 6.14.10

**Comment by peterthehan** [comment]
Unable to reproduce on v1.1.3. Something in https://github.com/peterthehan/runescape-text/commit/0fd59a53bb0bb6a3ce28c79ebd3255431c4c0e33 fixed this, closing.
